--- #YAML:1.0
name: Algorithm-Interval2Prefix
version: 0.01
license: perl
distribution_type: module
requires:
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Algorithm::Interval2Prefix:
    file: Interval2Prefix.pm
    version: 0.01
generated_by: Module::Build version 0.21
